name: Create Release

on:
  push:
    tags:
      - '*'
    branches: [ "master" ]
    paths:
      - 'Source-Files/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Source-Files/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
     
    - name: Restore NuGet Packages
      run: nuget restore DaRT.sln
      working-directory: ./Source-Files
 
    - name: Build and Publish Web App
      run: msbuild DaRT.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:DebugSymbols=false /p:DebugType=None
      working-directory: ./Source-Files
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DaRT
        path: Source-Files\bin\Release

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: DaRT
          path: ./build-artifact

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build-artifact
          asset_name: DaRT.zip
          asset_content_type: application/zip